package cmd

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

// newTestCmd returns a command wired to capturable stdout/stderr buffers.
func newTestCmd() (*cobra.Command, *bytes.Buffer, *bytes.Buffer) {
	var out, errb bytes.Buffer
	c := &cobra.Command{}
	c.SetOut(&out)
	c.SetErr(&errb)
	return c, &out, &errb
}

func TestDumpCmd(t *testing.T) {
	c, out, errb := newTestCmd()
	if err := dumpCmd.RunE(c, []string{"go", "nope"}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(out.String(), "### Go ###") {
		t.Errorf("expected canonical header on stdout:\n%s", out.String())
	}
	if !strings.Contains(errb.String(), `template "nope" not found`) {
		t.Errorf("expected not-found on stderr:\n%s", errb.String())
	}

	c, _, _ = newTestCmd()
	if err := dumpCmd.RunE(c, []string{"nope"}); err == nil {
		t.Error("expected error when nothing found")
	}
}

func TestListCmd(t *testing.T) {
	c, out, _ := newTestCmd()
	if err := listCmd.RunE(c, nil); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	for _, want := range []string{"Available templates:", "Common", "Go", "Secrets"} {
		if !strings.Contains(out.String(), want) {
			t.Errorf("list output missing %q:\n%s", want, out.String())
		}
	}
}

func TestSearchCmd(t *testing.T) {
	c, out, _ := newTestCmd()
	if err := searchCmd.RunE(c, []string{"ru"}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	s := out.String()
	if !strings.Contains(s, "Ruby") || !strings.Contains(s, "Rust") {
		t.Errorf("expected Ruby and Rust:\n%s", s)
	}
	if strings.Contains(s, "Go") {
		t.Errorf("Go should not match 'ru':\n%s", s)
	}

	c, out, _ = newTestCmd()
	_ = searchCmd.RunE(c, []string{"zzz"})
	if !strings.Contains(out.String(), "No templates matching") {
		t.Errorf("expected no-match message:\n%s", out.String())
	}
}

func resetInitFlags(out string) { initForce, initAppend, initOutput = false, false, out }

func TestInitCmd(t *testing.T) {
	dir := t.TempDir()
	target := filepath.Join(dir, ".dockerignore")

	// lowercase resolves to canonical
	resetInitFlags(target)
	c, _, _ := newTestCmd()
	if err := initCmd.RunE(c, []string{"go"}); err != nil {
		t.Fatalf("lowercase go failed: %v", err)
	}
	if b, _ := os.ReadFile(target); !strings.Contains(string(b), "### Go ###") {
		t.Errorf("expected canonical Go header:\n%s", b)
	}

	// refuse existing file without --force
	resetInitFlags(target)
	c, _, _ = newTestCmd()
	if err := initCmd.RunE(c, []string{"go"}); err == nil {
		t.Error("expected refusal on existing file without --force")
	}

	// --force overwrites
	resetInitFlags(target)
	initForce = true
	c, _, _ = newTestCmd()
	if err := initCmd.RunE(c, []string{"node"}); err != nil {
		t.Fatalf("--force failed: %v", err)
	}
	b, _ := os.ReadFile(target)
	if strings.Contains(string(b), "### Go ###") || !strings.Contains(string(b), "### Node ###") {
		t.Errorf("force did not overwrite:\n%s", b)
	}

	// --append keeps single header
	resetInitFlags(target)
	initAppend = true
	c, _, _ = newTestCmd()
	if err := initCmd.RunE(c, []string{"python"}); err != nil {
		t.Fatalf("--append failed: %v", err)
	}
	b, _ = os.ReadFile(target)
	s := string(b)
	if !strings.Contains(s, "### Node ###") || !strings.Contains(s, "### Python ###") {
		t.Errorf("append lost content:\n%s", s)
	}
	if n := strings.Count(s, "# Generated by dibo"); n != 1 {
		t.Errorf("header should appear once, got %d", n)
	}

	// --force and --append are mutually exclusive
	resetInitFlags(target)
	initForce, initAppend = true, true
	c, _, _ = newTestCmd()
	if err := initCmd.RunE(c, []string{"go"}); err == nil {
		t.Error("expected error when both --force and --append set")
	}
}

func TestTemplateCompletion(t *testing.T) {
	got, dir := templateNames(nil, nil, "")
	if dir != cobra.ShellCompDirectiveNoFileComp {
		t.Errorf("unexpected directive: %d", dir)
	}
	has := func(s string) bool {
		for _, g := range got {
			if g == s {
				return true
			}
		}
		return false
	}
	if !has("Go") || !has("Secrets") {
		t.Errorf("expected Go and Secrets in completion: %v", got)
	}

	got2, _ := templateNames(nil, []string{"go"}, "")
	for _, g := range got2 {
		if g == "Go" {
			t.Errorf("Go should be excluded when already provided: %v", got2)
		}
	}
}
