package cmd

import (
	"fmt"
	"os"

	"github.com/anton-fuji/dibo/internal/templates"
	"github.com/spf13/cobra"
)

const defaultOutput = ".dockerignore"

var (
	initForce  bool
	initAppend bool
	initOutput string
)

var initCmd = &cobra.Command{
	Use:               "init [templates...]",
	Short:             "Create a .dockerignore file",
	Args:              cobra.MinimumNArgs(1),
	ValidArgsFunction: templateNames,
	RunE: func(cmd *cobra.Command, args []string) error {
		errOut := cmd.ErrOrStderr()

		if initForce && initAppend {
			return fmt.Errorf("--force and --append cannot be used together")
		}

		body, missing, err := templates.Combine(args)
		if err != nil {
			return err
		}
		for _, m := range missing {
			_, _ = fmt.Fprintf(errOut, "Warning: template %q not found, skipping...\n", m)
		}

		if initAppend {
			if err := appendToFile(initOutput, body); err != nil {
				return err
			}
		} else {
			if !initForce {
				if _, statErr := os.Stat(initOutput); statErr == nil {
					return fmt.Errorf("%s already exists; use --force to overwrite or --append to add", initOutput)
				} else if !os.IsNotExist(statErr) {
					return fmt.Errorf("stat %s: %w", initOutput, statErr)
				}
			}
			content := "# Generated by dibo\n\n" + body
			if err := os.WriteFile(initOutput, []byte(content), 0o644); err != nil {
				return fmt.Errorf("write %s: %w", initOutput, err)
			}
		}

		_, _ = fmt.Fprintf(cmd.OutOrStdout(), "%s written successfully\n", initOutput)
		return nil
	},
}

// appendToFile appends body to path, surfacing both write and close errors.
func appendToFile(path, body string) error {
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return fmt.Errorf("open %s: %w", path, err)
	}
	_, writeErr := f.WriteString(body)
	closeErr := f.Close()
	if writeErr != nil {
		return fmt.Errorf("append to %s: %w", path, writeErr)
	}
	if closeErr != nil {
		return fmt.Errorf("close %s: %w", path, closeErr)
	}
	return nil
}

func init() {
	initCmd.Flags().BoolVarP(&initForce, "force", "f", false, "overwrite the file if it already exists")
	initCmd.Flags().BoolVarP(&initAppend, "append", "a", false, "append to the file instead of overwriting")
	initCmd.Flags().StringVarP(&initOutput, "output", "o", defaultOutput, "output file path")
	rootCmd.AddCommand(initCmd)
}
