package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/anton-fuji/dibo/internal/templates"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init [templates...]",
	Short: "Create a .dockerignore file",
	Args:  cobra.MinimumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var finalContent strings.Builder
		finalContent.WriteString("# Generated by dibo\n\n")

		foundCnt := 0
		for _, arg := range args {
			filename := fmt.Sprintf("%s.dockerignore", arg)
			content, err := templates.FS.ReadFile(filename)
			if err != nil {
				fmt.Printf("Warning: Template '%s' not found, skipping...\n", arg)
				continue
			}
			finalContent.WriteString(fmt.Sprintf("### %s ###\n", arg))
			finalContent.Write(content)
			finalContent.WriteString("\n")
			foundCnt++
		}

		if foundCnt == 0 {
			return fmt.Errorf("no valid templates found")
		}

		err := os.WriteFile(".dockerignore", []byte(finalContent.String()), 0644)
		if err != nil {
			return fmt.Errorf("failed to write .dockerignore: %w", err)
		}

		fmt.Println(".dockerignore file created successfully!")
		return nil
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
}
